"""deleted the isadult table

Revision ID: f9933946d61f
Revises: edb00f0c1ff3
Create Date: 2025-10-18 00:52:24.657794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9933946d61f'
down_revision = 'edb00f0c1ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isAdult')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdult', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
